spec-version: 0.36.0

name:                stacked
version:             0.1.0
author:              ["Arnaud Spiwack"]
synopsis:            "A modern indexed monad stack"
maintainer:          arnaud.spiwack@tweag.io

github: tweag/pup/stacked
copyright: "(c) Modus Create LLC and its affiliates"

language: GHC2021

dependencies:
  - base
  - comonad
  - mtl
  - megaparsec
  - containers
  - prettyprinter
  - text

library:
  source-dirs: src

ghc-options: "-Wall"
